import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Stiven's Hotel",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section
      className={`--font-poppins font-poppins bg-secondary flex items-center justify-center min-h-screen`}
    >
      {children}
    </section>
  );
}
