FROM eclipse-temurin:21-jdk-alpine-3.22 AS builder

WORKDIR /app

COPY . .

# Converte terminações de linha CRLF para LF (necessário quando desenvolvendo no Windows)
RUN sed -i 's/\r$//' ./gradlew && chmod +x ./gradlew
RUN ./gradlew bootJar --no-daemon

FROM eclipse-temurin:21-jre-alpine-3.22

WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]
